contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: ""
    url: https://google.com
    about: Discussion about the nf-core/skierfe pipeline
